[package]
name = "MSBT-yuina"
version = "0.1.0"
edition = "2021"
authors = ["MSBT"]
description = "Simple Image Viewer"

[build-dependencies]
embed-resource = "2.2"

[profile.release]
opt-level = 'z'     # 最小サイズ最適化
lto = true          # Link Time Optimization を有効化
codegen-units = 1   # 単一ユニットでコンパイル
panic = 'abort'     # パニック時のスタックトレース機能を無効化
strip = true        # デバッグシンボルを削除

[dependencies]
eframe = "0.24.1"
image = "0.24.7"
log = "0.4.20"
env_logger = "0.10.1"
ico = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.8"
rfd = "0.12.1"
egui = { version = "0.24.1", default-features = false }
winapi = { version = "0.3.9", features = ["winuser", "windef"] }
log4rs = "1.2.0"
chrono = "0.4"
resvg = "0.44.0"
usvg = "0.44.0"
tiny-skia = "0.11.3"
